Update notes for submitted changes
* Mark messages as failed if SIM is inactive
* Fix creating a new conversation including own number
* Messaging: Show quick reply choices only on wearable devices
* Messaging: Add "Mark as read" quick action for message notifications
* Messaging: Contact Colors
* Messaging: Use a DayNight launch theme
* Messaging: disable auto dark theming on message bubble
* Messaging: allow framework to do dark theming automatically
* Messaging: Require external legacy storage
* Messaging: bump target SDK version to 29
* Messaging: Add sysconfig whitelist xml
* Messaging: Notification channel string fixes
* Messaging: Implement per conversation channels. Update API level to 28.
* Don't build with platform certificate
* Messaging: use white nav bar
* MediaPicker: Check for NPE
* Play an audible notification on receiving a class zero message.
* Messaging: bring back accent color
* Messaging: Toggable keyboard emoticons access
* Messaging: Implement option for swipe right to delete.
* Fix NoSuchMethodError for getTypeInfo()
* Remove advanced category if no preference
* AOSP/Messaging - Changed minSdkVersion to 19.
* Fix SecurityException at getActiveSubscriptionInfoList() on N and O
* Fix app initialization issue if no permissions
* AOSP/Messaging - Changed midSdkVersion to 14 and reverted to using Telephony.Carriers.CONTENT_URI instead of  Telephony.Carriers.SIM_APN_URI.
* Remove only one Lambda Exp for JAVA 7
* Fix handling format based on API level accordingly.
* Fix creating ConnectivityUtil to work on any platform
* Fix missing computeIfAbsent() method in L_MR1 and M
* Remove unnecessary methods from MmsUtils
* Allow call to phone numbers or voice mail numbers only
* Check CONFIG_SEND_MULTIPART_SMS_AS_SEPARATE_MESSAGES always
* Fix ConcurrentModificationException
* Parse recipients from RESPOND_VIA_MESSAGE correctly
* Remove dead code
* Disallow making a call to emergency numbers
* Check whether dialable only
* Auto re-sending MMS for all the transient failures
* Rescheduling pending messages after outside window failure
* Fix NPE on MultiConversationNotificationState
* Hide APN prefs if platform APIs are used
* Use ic_add_white for consistency instead
* Fix to show APN prefs correctly
* Fix NPE
* Handle delivered messages as completed messages
* Dismiss SnackBar when detached
* Fix assert fail during onSaveInstanceState()
* Fix WindowLeaked issue on AttachmentPreview
* Fix undesirable ripple effect on GalleryGridView
* New interface to pick a contact as attachment
* ProcessPendingMessagesAction works based on subscriptions
* Allow intent shared subject or title to be mms subject
* Update runner to AndroidJUnittest